# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: ghcr.io/cirruslabs/flutter:3.10.2

definitions:
  steps:
    - step: &test
        name: "Test"
        script:
          - flutter test

pipelines:
  default:
    - step: *test
